## The fuctions calculate a inverse matrix and cache it for further retrival.


## makeCacheMAtrix takes a matrix and returns a list of four functions:
##      set saves the matrix and erases the previusly cache inverse.
##      get returns the original matrix.
##      setinvers saves the inverse matrix previusly calculated.
##      getinvers returns the inverse matrix.

makeCacheMatrix <- function(x = matrix()) {
		m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function() x
        setinvers <- function(solve) m <<- solve
        getinvers <- function() m
        list(set = set, get = get,
             setinvers = setinvers,
             getinvers = getinvers)
}


## cacheSolve takes the list of funtions generated by the makeChacheMatrix funtion
## and returns the inverse matrix.
## If the inverse matrix is cached, it's retrieved. If not, it's calculated and cached.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
		   m <- x$getinvers()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- solve(data, ...)
        x$setinvers(m)
        m
}
